Frontend/main/__init__.py
import os 
from flask import Flask
from dotenv import load_dotenv
from main.routes import main, poem, user

def create_app():
    app = Flask(__name__)
    load_dotenv()
    app.register_blueprint(main.app)

    app.config['API_URL'] = os.getenv('API_URL')
    return app

Frontend/main/routes/__init__.py
from flask import Flask

Frontend/main/routes/functions.py
from flask import request, current_app, redirect, url_for

import requests, json

def get_poems_by_id(id, page = 1, per_page = 10):
    api_url = f' {current_app.config["API_URL"]}/poems'

    data = {"id": id, "page": page, "per_page": per_page, "user_id": id}

    headers = get_headers(without_token = True)

    return requests.get(api_url, data = data, headers = headers)


def get__poem(id):
    api_url = f'{current_app.config["API_URL"]}/poem/{id}'

    headers = get_headers()

    return requests.get(api_url, headers = headers)

def get_poems(page = 1, per_page = 3):
    api_url = f'{current_app.config["API_URL"]}/poems'

    data = {"page": page, "per_page": per_page}

    headers = get_headers(without_token = True)

    return requests.get(api_url, data = data, headers = headers)

def delete_poem(id):
    api_url = f'{current_app.config["API_URL"]}/poems/{id}'
    headers = get_headers()

    return requests.delete(api_url, headers = headers)


def get_user_info(id):
    api_url = f' {current_app.config["API_URL"]}/users/{id}'

    headers = get_headers()

    return requests.get(api_url, headers = headers)

def get_user(id):
    api_url = f'{current_app.config["API_URL"]}/users/{id}'

    headers = get_headers()

    return requests.get(api_url, headers = headers)

def get_username(user_id):
    api_url = f'{current_app.config["API_URL"]}/users/{user_id}'

    headers = get_headers()

    user = json.loads(response.text)
    return user['firstname']


def get_qualifications_by_poem_id(id):
    api_url = f'{current_app.config["API_URL"]}/califications/{id}'

    data = {"poem_id": id}

    headers = get_headers(without_token = True)

    return requests.get(api_url, data = data, headers = headers)


def json_loads(response):
    return json.loads(response.text)


def get_headers(without_token = False):
    if without_token:
        return {'Content-Type': 'application/json', 'Accept': f'Bearer{jwt}'}
    else:
        return {'Content-Type': 'application/json'}
    
def get_token():
    return request.cookies.get('token')


def get_jwt():
    return request.cookies.get('jwt')

def get_user_id():
    return request.cookies.get('user_id')

def redirect_to(url):
    return redirect(url_for(url))

Frontend/main/routes/main.py
from flask import Flask, Blueprint, current_app, render_template, make_response, request, redirect, url_for
import requests
import json


app = Blueprint('app', __name__, url_prefix='/')

@app.route('/')
def index():
    api_url = f'{current_app.config["API_URL"]}/poems' 
    data = { "pag": 1, "p_pag": 10 }
    headers = { "Content-Type": "application/json" }
    response = requests.get(api_url, json=data, headers=headers)
    print(response.status_code)  
    print(response.text)
    poems = json.loads(response.text)
    print(poems)
    return render_template('main.html', poems=poems["poems"])


@app.route('/login', methods=['GET','POST'])
def login():
    if (request.method == 'POST'):
        email = request.form['email']
        password = request.form['password']
        print(email, password)

        if email != None and password != None: 
            #url que utilizamos en insomnia
            api_url = f'{current_app.config["API_URL"]}/auth/login'
            data = {"email" : email, "password" : password}
            headers = {"Content-Type" : "application/json"}
            response = requests.post(api_url, json = data, headers = headers) 
            print("login", response)
            if (response.ok): 

                response = json.loads(response.text)
                token = response["access_token"]
                user_id = str(response["id"])

                response = make_response(redirect(url_for('app.user_main')))
                response.set_cookie("access_token", token)
                response.set_cookie("id", user_id)
                return response
                #return render_template('login.html')
        return(render_template('login.html', error = "Usuario o contraseña incorrectos"))
    else:
        return render_template('login.html')

@app.route('/register')
def register():
    return render_template('register.html')

''' 
@app.route('/home')
def user_main():
    if request.cookies.get('access_token'):
        api_url = f'{current_app.config["API_URL"]}/poems' 
        data = { "pag": 1, "p_pag": 10 }
        headers = { "Content-Type": "application/json" }
        response = requests.get(api_url, json=data, headers=headers)
        print(response.status_code)  
        print(response.text)
        poems = json.loads(response.text)
        print(poems)
        return render_template('main.html', poems=poems["poems"])    
    else:
        return redirect(url_for('app.login'))
'''

@app.route('/profile')
def user_profile():
    if request.cookies.get('access_token'):
        api_url = f'{current_app.config["API_URL"]}/poems'
        
        data = { "pag": 1, "p_pag": 10 }

        headers = { "Content-Type": "application/json" }

        response = requests.get(api_url, json=data, headers=headers) 
        
        return render_template('user_profile.html', poems = ["Poems"])
    else:
        return redirect(url_for('app.login'))

@app.route('/view/poem/<int:id>', methods=['GET'])
def view_poem(id):
    api_url = f'{current_app.config["API_URL"]}/poem/{id}'
    headers = {"Content-Type" : "application/json"}
    response = requests.get(api_url, headers=headers)
    poem = json.loads(response.text)
    return render_template('poem.html', poem = poem)

@app.route('/logout')
def logout():
    req = make_response(redirect(url_for('app.index')))
    req.delete_cookie("access_token")
    req.delete_cookie("id")
    return req

@app.route('/poem/create', methods=['GET','POST'])
def create_poem():
    jwt = request.cookies.get('access_token')
    if jwt:
        if request.method == 'POST':
            titulo = request.form['titulo']
            cuerpo = request.form['cuerpo']
            print(titulo)
            print(cuerpo)
            user_id = request.cookies.get("id")
            print(user_id)
            data = {"titulo": titulo, "cuerpo": cuerpo, "user_id": user_id  }
            print(data)
            headers = {"Content-Type" : "application/json", "Authorization" : f"Bearer {jwt}"}
            if titulo != "" and cuerpo != "":
                response = requests.post(f'{current_app.config["API_URL"]}/poems', json=data, headers=headers)
                print(response)
                if response.ok:
                    response = json.loads(response.text)
                    return redirect(url_for('app.view_poem', id=response["id"], jwt=jwt))
                else:
                    return redirect(url_for('app.create_poem'))
            else:
                return redirect(url_for('app.create_poem'))
        else:
            return render_template('update.html', jwt=jwt)
    else:
        return redirect(url_for('app.login'))

@app.route('/poem/<int:id>/delete')
def delete_poem(id):
    if request.cookies.get('accsess_token'):
        api_url = f'{current_app.config["API_URL"]}/poem/{id}'
        headers = {"Content-Type" : "application/json"}
        response = requests.delete(api_url, headers=headers)
        return response

Frontend/main/routes/poema.py
from flask import Blueprint, render_template

poema = Blueprint('poema', __name__, url_prefix="/poema")

@poema.route('/')
def index():
    return render_template('poem.html')

@poema.route('/poema/<id>')
def poem(id):
    return render_template('poem.html')

Frontend/main/routes/usuario.py
from flask import Blueprint, render_template, request

author = Blueprint('user', __name__, url_prefix="/usuario")

@author.route('/')
def index():
    return render_template('index.html')

@author.route('/usuario/<id>')
def profile(id):
    return render_template('user_profile.html')

Frontend/main/templates/all_poems.html
{% extends 'index.html' %}
  

  {%block content%} 

  <div class="container">
        <div class="row">
            <div class="col">
                <table class="table table-hover text-dark align-middle">
                    <tr class="table-secondary">
                        <th><select class="form-select" aria-label="Default select example">
                            <option selected>Titulo</option>
                            <option value="1">Asc</option>
                            <option value="2">Desc</option></select>
                        </th>
                        <th><select class="form-select" aria-label="Default select example">
                            <option selected>Autor</option>
                            <option value="1">Asc</option>
                            <option value="2">Desc</option></select>
                        </th>
                          <th><select class="form-select" aria-label="Default select example">
                            <option selected>Fecha</option>
                            <option value="1">Asc</option>
                            <option value="2">Desc</option>
                          </select></th>
                          <th><select class="form-select" aria-label="Default select example">
                            <option selected>Ranking</option>
                            <option value="1">Asc</option>
                            <option value="2">Desc</option>
                          </select></th>
                    </tr>
                    <tr>
                        <td>Titulo </td><td>Autor</td><td>Fecha </td><td>Ranking</td>
                    </tr>
                    <tr>
                        <td>Titulo </td><td>Autor </td><td>Fecha </td><td>Ranking </td>
                    </tr>
                    <tr>
                        <td>Titulo </td><td>Autor </td><td>Fecha </td><td>Ranking </td>
                    </tr>
                    <tr>
                        <td>Titulo </td><td>Autor</td><td>Fecha </td><td>Ranking </td>
                    </tr>
                    <tr>
                        <td>Titulo </td><td>Autor </td><td>Fecha </td><td>Ranking </td>
                    </tr>
                    <tr>
                        <td>Titulo </td><td>Autor </td><td>Fecha</td><td>Ranking </td>
                    </tr>                </table>
            </div>
        </div>
    </div>

    <nav aria-label="..." >
        <ul class="pagination justify-content-center">
            <li class="page-item">
            <a class="page-link" href="#">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active">
            <span class="page-link">2</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
            <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

Frontend/main/templates/index.html
<!doctype html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pag principal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/styles.css">
    {% endblock %}
</head>

    <body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="" >Hello World</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
            <a class="nav-link" href=" {{url_for('app.all_poems')}} ">Ver Poemas</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('app.login')}}">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('app.register')}}">Register</a>
            </li>
            <li class="nav-item">
            <a class="nav-link " href="{{url_for('app.user_profile')}}">Mi perfil</a>
            </li>
        </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}

{% endblock %} 



{% block scripts %}
 <!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/fe4eb8c452.js" crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
-->
{% endblock %}

Frontend/main/templates/login.html

{% extends 'index.html' %}
  

{%block content%} 
<div class="container">
  <div class="row d-flex justify-content-center">
      <div class="col-md-4 border bg-light p-4 mt-5 rounded text-dark">
          <form class="" method="POST" action="/login"> 
                <div class="mb-3">
                  <label for="email" class="form-label">Email</label>
                  <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter e-mail">
                </div>
                <div class="mb-3">
                  <label for="password" class="form-label">Password</label>
                  <input type="password" name="password"class="form-control" id="password" aria-describedby="emailHelp" placeholder="Enter password">
                </div>
              <div class="d-grid">
                  <button class="btn btn-primary" type="submit">Enviar</button>
              </div>
            </form> 
      </div>
  </div>



{% endblock %} 

Frontend/main/templates/main.html

{% extends 'index.html' %}
  

{%block content%} 




    <div class="card" style="width: 18rem;">
      
      <div class="card-body">
        <h5 class="card-title">Ultimo poema</h5>
        <p class="card-text"></p>
        <a href="poem.html" class="btn btn-primary">Ver</a>
      </div>
    </div>

    <div class="card" style="width: 18rem;">
      
      <div class="card-body">
        <h5 class="card-title">>Poema mejor rankeado del mes"</h5>
        <p class="card-text"></p>
        <a href="poem.html" class="btn btn-primary">Ver</a>
      </div>
    </div>

    <div class="card" style="width: 18rem;">
      
      <div class="card-body">
        <h5 class="card-title">Poema aleatorio</h5>
        <p class="card-text"></p>
        <a href="poem.html" class="btn btn-primary">Ver</a>
      </div>
    </div>


{% endblock %} 





Frontend/main/templates/poem.html

{% extends 'index.html' %}
  

{%block content%} 






    <div class="banner" >
        
        <ul>
            <li>Titulo</li>
            <li>Autor</li>
            <li>Fecha</li>
            <li>Rankimg</li>
            
        </ul>
        <button class="boton">algo</button>
    </div>

{% endblock %} 

Frontend/main/templates/register.html

{% extends 'index.html' %}
  

{%block content%} 





    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-4 border bg-light p-4 mt-5 rounded text-dark">
                <form class="" method="POST"> 
                    <div class="mb-3">
                        <label for="name">Nombre</label>
                        <input type="text" id="name" class="form-control" aria-describedby="emailHelp" placeholder="Enter name">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email address">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Contraseña</label>
                        <input type="password" class="form-control" id="password" aria-describedby="passwordHelp" placeholder="Enter password">
                    </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                </form> 
            </div>
        </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


{% endblock %} 

Frontend/main/templates/update.html
{% extends 'index.html' %}

{% block head %}

{% endblock %}

{% block content %}

<body>
    <main class="d-flex flex-colum main-bg shadow">
        <div class="banner">
            <article class="col-md-8">
            <section>
                <form method="POST" id="form2" action="/upload">
                    <div class="card">
                        <div class="poem-title">
                            <div class="poemtitle">
                                <input class="form-control" type="poemtitle" name="titulo" placeholder="Titulo del poema">
                            </div>
                            <div class="poembody">
                                <textarea class="form-control" name="body" rows="3" placeholder="Ingresar su poema"></textarea>
                            </div>
                        </div>
                    </div>
                    <div id="btn-post">
                        <button class="btn btn-primary btn-primary-outline-success" type="submit">POST</button>
                    </div>
                </form>
                  
            </section>
        </article>
</body>
{% endblock %}
Footer

Frontend/main/templates/user_profile.html

{% extends 'index.html' %}
  

{%block content%} 
 



    

    <div class="container">
        <fieldset disabled>
          <div class="row justify-content-center">
            <div class="form-group col-md-4">
              <label for="name">Nombre de usuario</label>
              <input type="text" class="form-control" placeholder="">
            </div>
            <div class="form-group col-md-4">
              <label for="email">E-mail</label>
              <input type="email" class="form-control" placeholder="">
            </div>
          </div>
          <div class="row justify-content-center mt-5">
            <div class="from-group col-md-4">
              <label for="poems">Mis poemas</label>
              <input type="number" class="form-control" placeholder="">
            </div>
            <div class="form-group col-md-4">
              <label for="qualifications">Calificaciones</label>
              <input type="number" class="form-control" placeholder="">
            </div>
          </div>
        </fieldset>
      </div>


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}